#!/usr/bin/env bash
# This script creates an RSA key pair
#!/bin/bash

# Name of the private key
private_key="school"

# Number of bits in the created key
key_bits=4096

# Passphrase
passphrase="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b "$key_bits" -f "$private_key" -N "$passphrase"

